version: '3'
services:
  worker:
    build:
      context: docker/worker
    image: kriterion-worker
    tty: true
  api:
    build:
      context: docker/api
    image: kriterion-api
    tty: true
    ports:
      - "4567:4567"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  restmq:
    image: pablozaiden/restmq:latest
    ports:
      - "6379:6379"
      - "8888:8888"
