version: '3'
services:
  worker:
    build: .
    tty: true
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  restmq:
    image: pablozaiden/restmq:latest
    ports:
      - "6379:6379"
      - "8888:8888"
