#!/usr/bin/env ruby

require 'criterion/cli'

begin
  Criterion::CLI.command.run(ARGV)
rescue Interrupt
  $stderr.puts "Aborted!"
  exit(1)
rescue SystemExit => e
  exit(e.status)
rescue Exception => e
  $stderr.puts "\nError while running: #{e.inspect}"
  $stderr.puts e.backtrace.join("\n").red if ARGV.include? '--trace'
  exit(1)
end
